added test step

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,10 +33,36 @@ jobs:
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
           docker build -t $IMAGE_NAME .
           docker push $IMAGE_NAME
+  test:
+    runs-on: ubuntu-latest
+    env: 
+      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/schedule_composer_backend:${{ github.sha }}
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run docker container
+        run: |
+          docker run -d --name test_container -p 8080:8080 $IMAGE_NAME
+          sleep 5 
+          docker ps -a
+
+      - name: Check if container is running
+        run: |
+          if [ "$(docker inspect -f '{{.State.Running}}' test_container)" != "true" ]; then
+            echo "Test Failed!"
+            exit 1
+          fi
+
+      - name: Cleanup
+        run: |
+          docker stop test_container
+          docker rm test_container
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build
+    needs: test
     env: 
       IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/schedule_composer_backend:${{ github.sha }}
     steps:
@@ -65,7 +91,7 @@ jobs:
           source: ".env"
           target: "/home/ubuntu"
 
-      - name: Deploy on Server
+      - name: Deploy on server
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
